### ISSUE TITLE
DevTools Roadmap

### ISSUE THREAD

**Issue by webfansplz** [vuejs/devtools#3]
This is a live list that will be updated accordingly:

- [x]  UI package (@alexzhang1030 )
- [x] Browser extension (@webfansplz )
    - [x]  panel mode
    - [x]  popup page
    - [x]  view mode support (overlay & panel)
- [x]  Core (@webfansplz )
    - [x]  Bridge messaging
    - [x]  Vue hook
- [x] DevTools Client (@webfansplz @alexzhang1030 )
- [x]  Vite plugin (@webfansplz )
- [ ] **[In Progress]** Plugin API (@webfansplz )
- [x] Electron App
- [x] SSR Support
- [ ] [Low Priority] Webpack plugin
- [ ] Others
   <del>Vue2 support (As not planned)</del>
